### ISSUE TITLE
The game crashes when I use the ranged weapons.

### ISSUE THREAD

**Issue by GDHJDSYDH** [fzzyhmstrs/ac#4]
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find attribute amethyst_core:damage_multiplication
	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.wrapOperation$zce000$amethyst_core$applyMultiplicationAttributeToDamage(class_1309.java:4659) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6074(class_1309.java:1683) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1163) ~[client-intermediary.jar:?]
	at net.reimaden.arcadiandream.entity.custom.danmaku.AmuletBulletEntity.applyDamage(AmuletBulletEntity.java:44) ~[arcadiandream-1.20.1-0.0.10.jar:?]
	at net.reimaden.arcadiandream.entity.custom.danmaku.BaseBulletEntity.method_7454(BaseBulletEntity.java:97) ~[arcadiandream-1.20.1-0.0.10.jar:?]
	at net.minecraft.class_1676.method_7488(class_1676.java:153) ~[client-intermediary.jar:?]
	at net.reimaden.arcadiandream.entity.custom.danmaku.BaseBulletEntity.method_7488(BaseBulletEntity.java:120) ~[arcadiandream-1.20.1-0.0.10.jar:?]
	at net.minecraft.class_1682.method_5773(class_1682.java:65) ~[client-intermediary.jar:?]
	at net.reimaden.arcadiandream.entity.custom.danmaku.BaseBulletEntity.method_5773(BaseBulletEntity.java:61) ~[arcadiandream-1.20.1-0.0.10.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more

**Comment by fzzyhmstrs** [comment]
This seems to be caused by some mod adding attributes to LivingEntity improperly, causing my attributes to be excluded.

can you provide the full log, including the mod-list please? And if you have any mods you suspect add attributes, please let me know to narrow my search.

**Comment by GDHJDSYDH** [comment]
I checked, maybe it was an issue caused by the beta version of Aquamirae and Obscure API, after I updated them, the problem seemed to disappear. I suggest you check out the compatibility between AC and these two mods.

**Comment by fzzyhmstrs** [comment]
Thank you for the information. I will follow up on those mods and check.

**Comment by fzzyhmstrs** [comment]
Confirmed that this issue is caused by a specific version of Obscure API/Aquamirae. They have since fixed it.
