### ISSUE TITLE
The game crashed whilst ticking entity Error: java.lang.IllegalArgumentException: Can't find attribute amethyst_core:player_experience

### ISSUE THREAD

**Issue by GitUser14975** [fzzyhmstrs/ac#5]
Quilt 1.20.1
The crash occurs every time I try to join a world

Here's the crash log:
https://gist.github.com/TenKotowsky/3e32678113d5a65b207e79194288bdbc

This is when I try to join the world after it has been generated. When I'm automatically joined it after creation I see this:
![image](https://github.com/fzzyhmstrs/ac/assets/100159503/e50304c5-c546-4e7f-a585-9905248ee000)

And also this is in the latest.log file
```
[13:12:54] [Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: Can't find attribute amethyst_core:player_experience
	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1657.localvar$eed000$amethyst_core$modifyXpUsingAttribute(class_1657.java:15916) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1657.method_7255(class_1657.java:1792) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3222.method_7255(class_3222.java:1147) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_170.method_748(class_170.java:47) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2985.method_12878(class_2985.java:181) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_179$class_180.method_796(class_179.java:35) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4558.method_22510(class_4558.java:74) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2135.method_9141(class_2135.java:30) ~[transformed-mod-minecraft.i0:0/:?]
	at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterCriteria.registerAll$lambda-0(RegisterCriteria.kt:46) ~[transformed-mod-amethyst-imbuement.i0:0/:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$3(ServerPlayConnectionEvents.java:51) ~[transformed-mod-quilted-fabric-networking-api-v1.i0:0/:?]
	at org.quiltmc.qsl.networking.api.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[transformed-mod-quilt-networking.i0:0/:?]
	at org.quiltmc.qsl.networking.impl.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:69) ~[transformed-mod-quilt-networking.i0:0/:?]
	at net.minecraft.class_3324.handler$enc000$quilt_networking$handlePlayerConnection(class_3324.java:9018) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.redirect$end000$quilt_networking$handlePlayerJoin(class_3248.java:2558) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by fzzyhmstrs** [comment]
If you've added Aquamirae and/or Obscure API, that's been a known cause of this issue recently.

**Comment by GitUser14975** [comment]
Oh yeah, I've got Aquamirae installed as well. Do I have to remove it or will this incomatibility get fixed soon?

**Comment by fzzyhmstrs** [comment]
I believe an Aquamirae/Obscure API update was put out that resolved the conflict

**Comment by BurnyLlama** [comment]
I also seem to be getting the same issue, but only when connecting to a server, not in single player:
```
java.lang.IllegalArgumentException: Can't find attribute amethyst_core:player_experience
	at net.minecraft.entity.attribute.DefaultAttributeContainer.require(DefaultAttributeContainer.java:22) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.attribute.DefaultAttributeContainer.getValue(DefaultAttributeContainer.java:28) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.attribute.AttributeContainer.getValue(AttributeContainer.java:76) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.LivingEntity.getAttributeValue(LivingEntity.java:1904) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.player.PlayerEntity.localvar$ekg000$amethyst_core$modifyXpUsingAttribute(PlayerEntity.java:22416) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.player.PlayerEntity.addExperience(PlayerEntity.java:1792) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerPlayerEntity.addExperience(ServerPlayerEntity.java:1147) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.AdvancementRewards.apply(AdvancementRewards.java:47) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.PlayerAdvancementTracker.grantCriterion(PlayerAdvancementTracker.java:181) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.Criterion$ConditionsContainer.grant(Criterion.java:35) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.AbstractCriterion.trigger(AbstractCriterion.java:74) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.TickCriterion.trigger(TickCriterion.java:30) ~[transformed-mod-minecraft.i0:0/:?]
	at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterCriteria.registerAll$lambda-0(RegisterCriteria.kt:46) ~[transformed-mod-amethyst-imbuement.i0:0/:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$3(ServerPlayConnectionEvents.java:51) ~[transformed-mod-quilted-fabric-networking-api-v1.i0:0/:?]
	at org.quiltmc.qsl.networking.api.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[transformed-mod-quilt-networking.i0:0/:?]
	at org.quiltmc.qsl.networking.impl.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:69) ~[transformed-mod-quilt-networking.i0:0/:?]
	at net.minecraft.server.PlayerManager.handler$cpi000$quilt_networking$handlePlayerConnection(PlayerManager.java:6518) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager.java:215) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler.java:131) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.md01b1de$quilt_registry$lambda$quilt$applySyncHandler$0$1(ServerLoginNetworkHandler.java:3553) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:782) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:764) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:743) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:25:46] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:49286
net.minecraft.util.crash.CrashException: Ticking player
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:574) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:269) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:259) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:172) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:908) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:283) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find attribute amethyst_core:player_experience
	at net.minecraft.entity.attribute.DefaultAttributeContainer.require(DefaultAttributeContainer.java:22) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.attribute.DefaultAttributeContainer.getValue(DefaultAttributeContainer.java:28) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.attribute.AttributeContainer.getValue(AttributeContainer.java:76) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.LivingEntity.getAttributeValue(LivingEntity.java:1904) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.player.PlayerEntity.localvar$ekg000$amethyst_core$modifyXpUsingAttribute(PlayerEntity.java:22416) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.entity.player.PlayerEntity.addExperience(PlayerEntity.java:1792) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerPlayerEntity.addExperience(ServerPlayerEntity.java:1147) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.AdvancementRewards.apply(AdvancementRewards.java:47) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.PlayerAdvancementTracker.grantCriterion(PlayerAdvancementTracker.java:181) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.Criterion$ConditionsContainer.grant(Criterion.java:35) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.AbstractCriterion.trigger(AbstractCriterion.java:74) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.advancement.criterion.TickCriterion.trigger(TickCriterion.java:30) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:566) ~[transformed-mod-minecraft.i0:0/:?]
	... 9 more
```

My mods:
```
 3dskinlayers-fabric-1.5.4-mc1.20.1.jar
 ad_astra-fabric-1.20.1-1.15.3.jar
 Ad-Astra-Giselle-Addon-fabric-1.20.1-5.3.jar
 AdditionalAdditions-6.0.1.jar
 AdditionalEnchantedMiner-1.20.1-fabric-20.0.801.jar
 additionallanterns-1.0.4a-fabric-mc1.20.jar
'AdditionalStructures-1.20.x-(v.4.2.0).jar'
 adorabuild-structures-1.20.1-fabric-1.0.1.jar
 Adorn-5.0.0+1.20.1-fabric.jar
 advancementinfo-1.20-fabric0.83.0-1.4.jar
 adventurez-1.4.18.jar
 ae2wtlib-15.0.1-beta.jar
 alessandrvenchantments-1.4.5.jar
 alloy-forgery-2.0.22+1.20.jar
 alternate-current-mc1.20-1.7.0.jar
 amethyst_core-1.2.1+1.20.1.jar
 amethystequipment-fabric-mc1.20.1-v1.0.10.jar
 amethyst_imbuement-1.20.1-09.jar
 amethyst-tools-v1.0_fabric+quilt_mc1.20.0.jar
 appleskin-fabric-mc1.20-2.5.0.jar
 appliedenergistics2-fabric-15.0.7-beta.jar
 architectury-9.1.12-fabric.jar
 arrowpopper-1.0.1.jar
 autoconfig1u-3.4.0.jar
 automated-crafting-1.4.13+MC1.20-1.20.1.jar
 automaticdoors-1.20.1-4.4.jar
 awesomedungeonend-fabric-1.20.1-3.1.1.jar
 awesomedungeon-fabric-1.20.1-3.2.0.jar
 awesomedungeonnether-fabric-1.20.1-3.1.1.jar
 awesomedungeonocean-fabric-1.20.1-3.3.0.jar
 azure-paxels-1.20.1-1.0.5.jar
 badpackets-fabric-0.4.1.jar
 baguette-1.1.4+1.20.1.jar
 balm-fabric-1.20-7.0.7.jar
 bclib-3.0.13.jar
 _bclib_deactivated
 bedrodium-0.2.2.jar
 betterbeds-1.3.0-1.19.3.jar
 bettercombat-fabric-1.7.3+1.20.1.jar
 better-end-4.0.10.jar
 BetterF3-7.0.1-Fabric-1.20.1.jar
 better-fabric-console-mc1.20.1-1.1.6.jar
 betterfpsdist-fabric-1.20.1-3.9.jar
 BetterFurnaces-1.20.1-1.0.2-fabric.jar
 bettermounthud-1.2.2.jar
 better-nether-9.0.9.jar
 BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
 bettersafebed-fabric-1.20-8.jar
 bikes-1.0.0.jar
 biomemakeover-FABRIC-1.20.1-1.10.2.jar
 blahaj-quilt-1.20.1-0.3.0.jar
 blockus-2.7.5+1.20.1.jar
 blur-3.1.0.jar
 BOMD-1.7.2-1.20.jar
 Bookshelf-Fabric-1.20.1-20.0.2.jar
 botarium-fabric-1.20.1-2.2.0.jar
 Bountiful-6.0.3+1.20.1-fabric.jar
 brazier-fabric-6.1.1.jar
 bsvsb-3.0.3.jar
 calibrated-1.2.2+1.20.jar
 CameraOverhaul-1.4.0-fabric-universal.jar
 can-i-mine-this-block-1.4.0.jar
 capymod-1.2.jar
 caracal-1.20-2.3.3.jar
 cardinal-components-api-5.2.2.jar
 carryon-fabric-1.20.1-2.1.1.3.jar
 cat_jam-1.1.3.jar
 charmofundying-quilt-6.4.3+1.20.1.jar
 chatcalc-3.0.15.jar
 chunkloaders-1.2.7-fabric-mc1.20.jar
 chunksending-fabric-1.20.1-2.6.jar
 Chunky-1.3.92.jar
 clickadv-fabric-1.20.1-3.3.jar
 cloth-config-11.1.106-fabric.jar
 Clumps-fabric-1.20.1-12.0.0.3.jar
 collective-1.20.1-6.65.jar
 command-config-0.1.0-beta.4+1.20.jar
 complete-bone-meal-2.1.1+1.20.1.jar
 completeconfig-2.5.0.jar
'Concrete Plus-1.9.8.jar'
 conjuring-1.0.28+1.20.jar
 connectivity-fabric-1.20.1-4.5.jar
 cooldown-coordinator-0.6.2.jar
 coxinhautilities-1.4.10+1.20.jar
 craftable-smitihing-templates-1.0-fabric.jar
 craftsaddles-fabric-mc1.20.1-v1.0.10.jar
 Croptopia-1.20.1-FABRIC-2.3.2.jar
 cupboard-fabric-1.20.1-1.7.jar
 customizableelytra-quilt-2.1.0+1.20.jar
 Debugify-1.20.1+2.0.jar
 deeper_dark-2.2.1.jar
 DEUF_Refabricated-MC1.20.1-1.1.0.jar
 doggo-mod-overhauled-5.2.1.jar
 dragonloot-1.1.4.jar
 ductwork-0.7.4.jar
 dungeons-and-taverns-v2.1.4.jar
 dynamiccrosshair-7.0.4+1.20-fabric.jar
 dynamiccrosshair-compat-3.3+1.20.1.jar
 dynamic-fps-2.4.0.jar
 edf-remastered-4.3.jar
 elytraslot-quilt-6.3.0+1.20.1.jar
 elytratrims-1.2.1+1.20.jar
 elytra_trinket-1.0.3.jar
 emi-1.0.19+1.20.1+fabric.jar
 emi_loot-0.6.5+1.20.1.jar
 emitrades-fabric-1.2.0+mc1.20.1.jar
 enderchests-fabric-1.20.1-1.0.jar
 endertanks-fabric-1.20.1-1.0.jar
 energizedpower-1.20.1-2.0.0-beta-2-fabric.jar
 enhancedblockentities-0.9+1.20.jar
 EnhancedWorkbenches-1.0+1.20.1.jar
 entityculling-fabric-1.6.2-mc1.20.jar
 exordium-fabric-1.1.3.1-mc1.20.1.jar
 explorations-fabric-1.20.1-1.5.2.jar
 ExplorersCompass-1.20.1-2.2.2-fabric.jar
 explorify-v1.3.0-mc1.20u1.20.1.jar
 extractinator-fabric-1.20-2.2.0.jar
 fabric-hammers-1.0.0.jar
 FactoryAPI-1.20.1-1.1.1-fabric.jar
 fastentitytransfer-fabric-1.20.x-1.2.1.jar
 fast-portals-1.0.3.jar
 ferritecore-6.0.0-fabric.jar
 ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
 FriendlyFire-Fabric-1.20.1-18.0.2.jar
 furnacerecycle-1.20.1-2.0.jar
 fzzy_core-0.2.5.1+1.20.1.jar
 geckolib-fabric-1.20.1-4.2.2.jar
 getittogetherdrops-fabric-1.20-1.3.1.jar
 gottagofast-1.1.0.jar
 gpumemleakfix-fabric-1.20.1-1.6.jar
 gravestones-v1.15.jar
 gtceu-fabric-1.20.1-1.0.11.a.jar
 harvestwithease-1.20.1-7.0.0.2-fabric.jar
 healingcampfire-1.20.1-5.1.jar
 heart-of-the-machine-2.0.0-alpha.7+1.20.1.jar
 held-item-info-1.5.0.jar
 icarus-1.16.jar
 igneous-machines-1.2.0+1.20.jar
 ImmediatelyFast-1.1.28+1.20.1.jar
 improvedsigns-1.3.1.jar
 imst-2.1.0.jar
 Incendium_1.20.1_v5.3.1.jar
 indium-1.0.25+mc1.20.1.jar
 indrev-1.16.3-BETA.jar
 indrev-nikolite-1.0+1.20.1.jar
 InfChest-Fabric-1.20.1-20.2.jar
 inspecio-1.8.1+1.20.jar
 instant-structures-1.0.0.jar
 InventoryCleaner-1.0.1-1.20.1.jar
 invhud.fabric.1.20-3.4.18.jar
 iris-mc1.20.1-1.6.8.jar
 ironbookshelves-1.20.1-1.1.2-fabric.jar
 ironchests-5.0.2-fabric.jar
 itemalchemy-0.7.2.jar
 itemcollectors-1.1.8-fabric-mc1.20.jar
 Jade-1.20-fabric-11.6.0.jar
 kaffees_dual_ride-1.1.0.jar
 Kambrik-6.1.1+1.20.1-fabric.jar
 kibe-1.10.1-BETA+1.20.jar
 krypton-0.2.3.jar
 lambdynamiclights-2.3.1+1.20.1.jar
 largefluidtank-fabric-20.5.1.jar
 LetSleepingDogsLie-1.20.1-Fabric-1.2.0.jar
 libraryferret-fabric-1.20.1-4.0.0.jar
 lighty-fabric-2.0.9+1.20.1.jar
 linkedstorage-1.5.2-1.20.jar
 lithium-fabric-mc1.20.1-0.11.2.jar
 livingthings-fabric-1.20.1-2.0.1.jar
 lootbagmod-4.0.0-1.20.1.jar
 LostFeatures-0.7.2.1-Fabric-1.20.1.jar
 lunade-fastanim-1.6-1.20.jar
 manic-1.1.0.jar
 mcdw-8.0.3.jar
 mcpitanlibarch-1.7.6-1.20.1-fabric.jar
 megacells-fabric-2.1.0-beta.4-1.20.1.jar
 memoryleakfix-fabric-1.17+-1.1.1.jar
 memorysettings-fabric-1.20.1-5.3.jar
 merequester-fabric-1.20.1-1.1.3.jar
 mes-1.1-1.20-fabric.jar
 MixinConflictHelper-1.2.0.jar
 mixintrace-1.1.1+1.17.jar
 mmcmga-1.20.1-1.0.jar
 mob-captains-v2.1.2.jar
 mobhealthbar-fabric-1.20.1-2.2.0.jar
 modelfix-1.14-fabric.jar
 modernfix-fabric-5.7.0+mc1.20.1.jar
 ModernKeyBinding-Fabric-1.20-1.2.0.jar
 Modifiers-fabric-1.20.1-0.1.3.jar
 modmenu-7.2.1.jar
 moonlight-1.20-2.8.4-fabric.jar
 MoreBows-1.0.11+1.20.x.jar
 morechathistory-1.19.1-1.1.1.jar
 moreculling-1.20.1-0.19.0.jar
 MoreCullingExtra-1.1-1.20.1.jar
 more-geodes-1.8.2.jar
 moremobvariants-fabric+1.20-1.2.2.jar
 moreswordsmod-0.0.2-1.20.1.jar
 MouseTweaks-fabric-mc1.20-2.25.jar
"Mo'ZombiesWave-1.20.1-0.1.0-fabric.jar"
 myloot-4.0.3-1.20.1.jar
 mythicmetals-0.18.2+1.20.jar
 mythicupgrades-fabric-1.8.1-1.20.1.jar
 name-visibility-1.1.0+1.19.4-1.20.jar
 NETS_0.3.5.5.jar
 notenoughanimations-fabric-1.6.4-mc1.20.jar
 notenoughcrashes-4.4.6+1.20.1-fabric.jar
'Nyctophobia_1.9_(FABRIC)_for_1.20+.jar'
 overloaded-1.1.1+1.19.3.jar
 owo-lib-0.11.1+1.20.jar
 packetunlimited-1.0.0.jar
 Patchouli-1.20.1-81-FABRIC.jar
 peculiar-pieces-1.2.17.jar
'Philips-Ruins1.20.1-1.9[Fabric].jar'
 pickable_villagers-1.4.3+1.20.1.jar
 piercingpaxels-1.0.12.jar
 PipePlus-1.20-0.5.5.jar
 plantinajar-2.5.3.jar
 player-animation-lib-fabric-1.0.2-rc1+1.20.jar
 plushables-fabric-mc1.20.1+1.1.2.jar
 plushie-mod-1.2.1.jar
 polymorph-quilt-0.49.0+1.20.1.jar
 portable-crafting-1.4.0+1.19.4.jar
 potionring-fabric-1.20-1.0.jar
 Powah-5.0.1.jar
 power-networks-2.0.1+mc.1.20.1.jar
 pressalttomeow-1.0.4.jar
 prettybeaches-fabric-1.20-11.0.1.jar
 puffish_skills-0.8.0-1.20-fabric.jar
 qfapi-7.1.2_qsl-6.1.1_fapi-0.87.0_mc-1.20.1.jar
 quartz-elevator-2.2.5+1.20.jar
 quilt-kotlin-libraries-2.1.2+kt.1.9.0+flk.1.10.8.jar
 quilt_loading_screen-6.0.0+1.20.1.jar
 quilt_tag_plus-0.2.2+1.20.1.jar
 rebalanced-loot-mc1.20-v1.1.jar
 RebornCore-5.8.7.jar
 reeses_sodium_options-1.6.4+mc1.20.1-build.94.jar
 repurposed_structures-7.1.1+1.20.1-quilt.jar
 resourcefulconfig-fabric-1.20.1-2.1.0.jar
 resourcefullib-fabric-1.20.1-2.1.9.jar
 scalable-cats-force-fabric-2.1.0.jar
 scarecrowsterritory-1.1.10-fabric-mc1.20.jar
 screenshot-to-clipboard-1.0.9-fabric.jar
 scriptor-0.6.6-1.21.1-sgd.jar
 securecrops-1.0.4+1.20.jar
 servercore-fabric-1.3.7+1.20.1.jar
 ShearableCows-1.0.0-1.20.1.jar
 shetiphiancore-fabric-1.20.1-1.0.jar
 SimpleCopperPipes-1.13.4.jar
 simplepipes-all-0.11.0-pre.2.jar
 SimpleVeinminer-1.4.2.jar
 SimplyHouses-1.1.4-1.20.1-fabric.jar
 simplyswords-fabric-1.50.0-1.20.1.jar
 SkyVillages-1.0.2.1-1.20.1-fabric.jar
 smallships-fabric-1.20.1-2.0.0-a2.3.3.jar
 smarterfarmers-1.20-1.7.3-fabric.jar
 smoothchunk-fabric-1.20.1-3.1.jar
 sodium-extra-0.5.1+mc1.20.1-build.112.jar
 sodium-fabric-mc1.20.1-0.5.2.jar
 soulslike-weaponry-0.9.9.6-1.20-fabric.jar
 spawnersplus-2.1.0-1.20.1.jar
 spelunker-1.5.3-mc1.20.jar
 spoornpacks-5.0-1.20.1.jar
 StackDeobfuscatorFabric-1.4.1+03a1fe4.jar
 stackrefill-1.20.1-4.0.jar
 starlight-1.1.2+fabric.dbc156f.jar
 Stellarity-v2-0d.jar
 structureessentials-fabric-1.20.1-3.0.jar
 subterrestrial-fabric-1.20-2.2.0.jar
 supermartijn642configlib-1.1.7-fabric-mc1.20.jar
 supermartijn642corelib-1.1.12b-fabric-mc1.20.jar
 tech_enhanced-1.0.3.jar
 TechReborn-5.8.7.jar
 tectonic-mod-mc1.19.3+-v2.1.jar
 TerraBlender-fabric-1.20.1-3.0.0.169.jar
 Terralith_1.20.1_v2.4.3.jar
 tesseract-1.0.35-fabric-mc1.20.jar
 things-0.3.1+1.20.jar
 tidal-towns-1.1.jar
 tlc-fabric-1.0.1-1.20.X.jar
 tms-1.0.0.jar
 travelers-backpack-1.20.1-9.1.2.jar
 trinkets-3.7.1.jar
 trofers-fabric-5.0.1.jar
 Trowel-1.1.0.jar
 twigs-3.1.0-fabric.jar
 umu_backpack-5.1-1.20.1.jar
 umu_little_maid-3.11a.jar
 UncraftingTable-fabric-1.2.6.jar
 uuextended-1.1.3.jar
 VariantFurnaces-1.2.0-1.20.1.jar
 villagernames-1.20.1-5.2.jar
 villagespawnpoint-1.20.1-4.0.jar
 vorpal-enchantment-1.20-3.0.3.jar
 wired-redstone-0.7.3+1.20.1.jar
 wirelesschargers-1.0.8-fabric-mc1.20.jar
 wirelessnetworks-1.7.1.jar
 wraith-fabricaeexnihilo-1.0.0-beta.4+mc1.20.1.jar
 wraith-silkspawners-1.1.3.jar
 Xaeros_Minimap_23.6.2_Fabric_1.20.jar
 XaerosWorldMap_1.33.0_Fabric_1.20.jar
 yacg-2023.7.3.jar
 yet-another-config-lib-fabric-3.1.0+1.20.jar
 your-reputation-0.2.4+jade.1.20.jar
 zmedievalmusic-fabric-1.20.1-2.1.jar
 Zoomify-2.11.0.jar
```

**Comment by BurnyLlama** [comment]
It should probably be noted that I use quilt.

**Comment by fzzyhmstrs** [comment]
Some other mod besides the ones mentioned above may be conflicting with me adding attributes to the PlayerEntity.

**Comment by BurnyLlama** [comment]
Well, I have a lot of mods -- if I happen to find out anything about it, I will try to remember to update... but with like 300 mods, it might take a while, if I deep in to the task...

**Comment by fzzyhmstrs** [comment]
I happen to be working on a version that tweaks how this works a bit. With this build artifact, do you still have the problem?
[New_Version.zip](https://github.com/fzzyhmstrs/ac/files/12385923/New_Version.zip)

**Comment by BurnyLlama** [comment]
This version seems to work, however, I also found that this mod https://www.curseforge.com/minecraft/mc-mods/deuf-refabricated caused issues -- maybe not related to this though. I believe it deduplicates stuff diffrently on client and server, causing desynchronization between items...

**Comment by fzzyhmstrs** [comment]
This has since been fixed with new versions of AC.
